image: node:12.3.1
pages:
  artifacts:
    paths:
      - build
  cache:
    paths:
      - .yarn-cache/
  only:
    - master
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn config set cache-folder $(pwd)/.yarn-cache
    - yarn install
    - yarn build
  stage: deploy
